{% set name = "fsleyes" %}
{% set version = "0.30.1" %}
{% set sha256 = "ff862287df8831012c0a83765b287d6bd442bbc2341ca82e9a937f7e7a6b7342" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - logging.patch

build:
  number: 0
  skip:       True  # [py27]
  osx_is_app: True
  entry_points:
    - render             = fsleyes.render:main
    - fsleyes            = fsleyes.main:main
    - fsleyes_unfiltered = fsleyes.filtermain:main


requirements:
  host:
    - python
    - pip
    - sphinx >=1.7
    - sphinx_rtd_theme
    - mock
  run:
    - python
    - python.app  # [osx]
    - tk !=8.6.9  # [osx]
    - fslpy >=2.4
    - fsleyes-props >=1.6.2
    - fsleyes-widgets >=0.6
    - jinja2 2.*
    - matplotlib >=1.5
    - nibabel >=2.3
    - numpy >=1.14
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing 2.*
    - scipy >=0.18
    - six 1.*
    - trimesh >=2.37.29
    - rtree 0.8.3.*
    - wxpython >=4
    - xnat >=0.3.3
    - wxnatpy >=0.3.0
    - indexed_gzip >=0.7
    - ipykernel >=4.8
    - ipython >=5
    - jupyter_client >=5.2
    - notebook >=5.5
    - pyzmq >=17.0
    - tornado >=5.0
    - dcm2niix 1.0.20181114

test:
  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.controls
    - fsleyes.plotting
    - fsleyes.profiles
    - fsleyes.views
  commands:
    - fsleyes -V
    - fsleyes -h

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FSL image viewer'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
