{% set version = "0.33.0" %}

package:
  name: fsleyes
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/f/fsleyes/fsleyes-{{ version }}.tar.gz
  sha256: 55e847c7092625cffe51fa1d96a069adf4513bd88ef52c89ffb34153af570e2e
  patches:
    - logging.patch

build:
  number: 0
  skip: true  # [py27]
  osx_is_app: true
  entry_points:
    - render             = fsleyes.render:main
    - fsleyes_unfiltered = fsleyes.main:main
    - fsleyes            = fsleyes.filtermain:main


requirements:
  host:
    - python
    - pip
    - sphinx >=1.7
    - sphinx_rtd_theme
    - mock
  run:
    - python
    - python.app  # [osx]
    - tk !=8.6.9  # [osx]
    - freeglut    # [linux or win]
    - fslpy >=2.8
    - fsleyes-props >=1.6.7
    - fsleyes-widgets >=0.8.4
    - jinja2 2.*
    - matplotlib-base >=1.5
    - nibabel >=2.3
    - numpy >=1.14
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing 2.*
    - scipy >=0.18
    - six 1.*
    - trimesh >=2.37.29
    - rtree >=0.8.3.*
    - wxpython >=4
    - xnat >=0.3.3
    - wxnatpy >=0.3.0
    - indexed_gzip >=0.7
    - ipykernel >=4.8
    - ipython >=5
    - jupyter_client >=5.2
    - notebook >=5.5
    - pyzmq >=17.0
    - tornado >=5.0
    - dcm2niix 1.0.20181114

test:
  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.controls
    - fsleyes.plotting
    - fsleyes.profiles
    - fsleyes.views
  commands:
    - fsleyes -V
    - fsleyes -h

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FSL image viewer
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
