{% set name = "fsleyes" %}
{% set version = "1.3.2" %}
{% set sha256 = "e9b2bd21aaa16362715d90e1e5021ac89353a340d1d22bcd8d5de02853aff83a" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/f/fsleyes/fsleyes-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - logging.patch
    - opengl.patch

build:
  number: 1
  skip: true  # [py<37]
  osx_is_app: true
  entry_points:
    - render             = fsleyes.render:main
    - fsleyes_unfiltered = fsleyes.main:main
    - fsleyes            = fsleyes.filtermain:main


requirements:
  host:
    - python
    - pip
    - sphinx >=1.7
    - sphinx_rtd_theme
    - mock
  run:
    - python
    - python.app              # [osx]
    - tk !=8.6.9              # [osx]
    - appnope                 # [osx]
    - pyobjc-core             # [osx]
    - pyobjc-framework-Cocoa  # [osx]
    - mesalib 18.*            # [linux]
    - fslpy >=3.6
    - fsleyes-props >=1.7.2
    - fsleyes-widgets >=0.12
    - file-tree >=0.3.5
    - file-tree-fsl >=0.1.5
    - jinja2 >=2.*
    - matplotlib-base >=1.5
    - nibabel >=2.3
    - numpy >=1.14
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing 2.*
    - scipy >=0.18
    - trimesh >=2.37.29
    - rtree >=0.8.3.*
    - wxpython >=4.0
    - xnat >=0.3.3
    - wxnatpy >=0.4.0
    - indexed_gzip >=0.7
    - ipykernel >=4.8
    - ipython >=5
    - jupyter_client >=5.3.1
    - notebook >=6
    - pyzmq >=17
    - tornado >=5
    - dcm2niix >=1.0.20181114

test:
  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.controls
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.plotting
    - fsleyes.plugins
    - fsleyes.profiles
    - fsleyes.views
#   source_files:
#     - fsleyes/assets/icons/app_icon.png
  commands:
    - fsleyes -V
    - fsleyes -h
#     - fsleyes render -of out.png fsleyes/assets/icons/app_icon.png  # [osx]

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FSL image viewer
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
