{% set name = "fsleyes" %}
{% set version = "1.12.5" %}
{% set sha256 = "b8b5ded15237b3ce23444c2dee6047699abc53da9403f073a116b4870d548c5b" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/f/fsleyes/fsleyes-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:

    # Set GDK_BACKEND=x11, as the conda-forge
    # wxwidgets package is built to use GLX
    # and not EGL for OpenGL interaction
    #
    # Add $PREFFIX/share/ to XDG_DATA_DIRS,
    # as this may not otherwise be found if
    # if XDG_DATA_DIRS is set on the host
    # platform.
    - envvars.patch

    # Disable/suppress logging, and disable
    # OpenGL error checking
    - logging.patch

    # Make sure the OpenGL libs can be found
    # on macOS, and allow execution of GUI
    # aps from non-framework python
    # installations.
    - opengl.patch

build:
  number: 2
  noarch: python
  osx_is_app: true
  entry_points:
    - render             = fsleyes.render:main
    - fsleyes_unfiltered = fsleyes.main:main
    - fsleyes            = fsleyes.filtermain:main


requirements:
  build:
    - sphinx >=1.7
    - sphinx_rtd_theme
    - mock
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - __{{ noarch_platform }}
    - python >=3.8
    {% if noarch_platform == "osx" %}
    - python.app
    - tk !=8.6.9
    - appnope ==0.1.*
    {% endif %}
    - fslpy >=3.19
    - fsleyes-props >=1.11
    - fsleyes-widgets >=0.14
    - file-tree >=0.3.5
    - file-tree-fsl >=0.1.5
    - jinja2 >=2
    - matplotlib-base >=3.5
    - nibabel >=2.3
    - numpy >=1.14
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing >=2
    - scipy >=0.18
    - trimesh >=2.37.29
    - rtree >=0.8.3
    - wxpython >=4.2.2
    - xnat >=0.3.3
    - wxnatpy >=0.4.0
    - indexed_gzip >=0.7
    - ipykernel >=4.8
    - ipython >=5
    - jupyter_client >=5.3.1
    - nbclassic
    - pyzmq >=17
    - tornado >=5
    - dcm2niix >=1.0.20181114

test:
  # need osmesa on linux
  {% if noarch_platform == "linux" %}
  requires:
    - mesalib
  {% endif %}
  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.controls
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.plotting
    - fsleyes.plugins
    - fsleyes.profiles
    - fsleyes.views
  source_files:
    - fsleyes/assets/icons/app_icon.png
  commands:
    - fsleyes -V
    - fsleyes -h
    # The conda-forge CI Windows
    # env does not have OpenGL
    {% if noarch_platform != "win" %}
    - fsleyes render -of out.png fsleyes/assets/icons/app_icon.png
    {% endif %}

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FSL image viewer
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
