{% set name = "fsleyes" %}
{% set version = "0.27.3" %}
{% set sha256 = "ed25bd60e7dfa185a7773315bb7630583718e4b08c281024183ca751fea479dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - logging.patch

build:
  number:     2
  osx_is_app: True
  entry_points:
    - render  = fsleyes.render:main
    - fsleyes = fsleyes.main:main


requirements:
  build:
    - python
    - pip
    - sphinx
    - sphinx_rtd_theme
    - mock

  run:
    - python
    - python.app  # [osx]
    - deprecation >=1
    - fslpy >=1.13.2
    - fsleyes-props >=1.6.2
    - fsleyes-widgets >=0.6
    - jinja2 2
    - matplotlib >=1.5
    - nibabel 2
    - numpy 1
    - pillow >=3.2.0
    - pyopengl >=3.1.0
    - pyparsing 2
    - scipy
    - six 1
    - trimesh >=2.22.28
    - rtree 0.8.3
    - wxpython >4
    - xnat >=0.3.3
    - wxnatpy >=0.3.0
    - indexed_gzip >=0.7
    - ipykernel
    - ipython
    - jupyter_client
    - notebook
    - pyzmq
    - tornado
    - dcm2niix

test:
  imports:
    - fsleyes
    - fsleyes.actions
    - fsleyes.displaycontext
    - fsleyes.editor
    - fsleyes.gl
    - fsleyes.controls
    - fsleyes.plotting
    - fsleyes.profiles
    - fsleyes.views
  commands:
    - fsleyes -V
    - fsleyes -h

app:
  entry: fsleyes
  summary: The FSL image viewer
  type: desk
  icon: logo.png

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FSL image viewer'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/

extra:
  recipe-maintainers:
    - pauldmccarthy
