travis:
  secure:
    BINSTAR_TOKEN: kTkx9JX7zdXHbHVMScOfl632XipEwiCLg+aJBAh83o+hR5G0Y30WEO61uj4kkNx86G/Km28ijcMzMlp6MTiCPTUMxDZ7Oltj2X7uGB80yybp83W0/pL2mOX8o59JbV9CbDC3HHcqQio/clw8c6teJBWlH5d7sWiNIOMQ0G4p3wwuAI9wxwoND1aKhuUJ2jqb5keZVxw5GskhRZEsJrQ6nzDHvVD2N3aG98pQ2nVtH7MrGcCeNs38gGREiefInUG5hJ6XJ51Kfr6B7aDtzNmaFZexyn7cg12CKlKdTgArobMzedkG8YHHNzOw/cCQGYNJpnxzRtE/uEPVLmmOKn+n+v2FpZHxTo52dIe9J79CILEiTofsS75yP8wG++oT1mD08Ueb+uogv+MkNgKpk5S3X0ta9XjEIGrBZF4eTMiR7OY285Fcb04BVQyySAcOQGcCUPBNHd2xUxOEzT4rQVGRU7qDL5eWasaOyG6VyouRBQHxt7awL+RAUFaH9iLCGU5imsprUhKZwrExu8CiUgbpZNDlRJka/050IqpV855UnPqKR5mZyXzIhR76zbIoW2GcRoRazKgt6nqVQp+PSH7v6ZsaguMLtnDNbiIHu374pg+t7yXa2KcSBFL9AMiDW042lo+3QTleDSYny6Gm4x8eB/uHMIt/rI2whw1EEGiv5KY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
